### PR TITLE
Add ngraph

### PR DESCRIPTION
**Pull request by ZECTBynmo**
https://github.com/anvaka/ngraph

ngraph is an amazing (and amazingly efficient) graph library that powers visualizations like this: https://anvaka.github.io/allnpmviz3d/

It contains pure a pure graph manipulation library
https://github.com/anvaka/ngraph.graph

Some excellent algorithms
https://github.com/anvaka/ngraph.cw
https://github.com/anvaka/ngraph.pagerank
https://github.com/anvaka/ngraph.louvain
https://github.com/anvaka/ngraph.hits

and much more

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

How is it mad science?

**Comment by ZECTBynmo** [comment]
I put it in mad science because it seemed most closely related to Cytoscape, which is already in that category. It also has a pretty wide range of capabilities, including raw graph manipulation, several rendering engines, clustering algorithms, and more, so it wasn't obvious else it should go.

**Comment by ZECTBynmo** [comment]
Is there any more info I can provide @sindresorhus?

**Comment by sindresorhus** [comment]
> Start the description with a capital and end with a full stop/period. - https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md

**Comment by sindresorhus** [comment]
I think the ngraph readme could use some work on marketing. From reading it I have no idea what problem it solves nor why I should care about it.

**Pull request closed without merging**
