### PR TITLE
Kefir.js

### PR DESCRIPTION
**Pull request by santacruz123**
Kefir is a Reactive Programming library for JavaScript inspired by Bacon.js and RxJS, with focus on high performance and low memory usage.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Kefir — is a Reactive Programming library for JavaScript inspired by Bacon.js and RxJS, with focus on high performance and low memory usage.

Not really sold on that. I see no reasoning how it actually differs from the rest. No proof of higher performance or lower memory usage.

**Comment by santacruz123** [comment]
It's another alternative, let others to decide whether to use it or not

**Comment by santacruz123** [comment]
Comparison - http://jsfiddle.net/jL1nm3c3/5/

**Comment by gartz** [comment]
I like it, very simple and well documented, I will give a try soon for a frontend project that already use some event stream based libs like https://github.com/gartz/pushStateTree (focus on handling browser navigation).

**Comment by ericsaboia** [comment]
+1
it seems nice IMHO.

**Comment by sindresorhus** [comment]
> It's another alternative, let others to decide whether to use it or not

That's not how it works. Just saying it's faster doesn't make it true. I can create a framework and call it "the best framework in the universe and all parallel dimensions", but that doesn't make it so. There needs to be some kind of evidence, preferably in your marketing. If I added every alternative it would no longer be a curation, and the list would lose its value.

-

I do like the API though, so happy to reconsider when you've gotten the 3.0 release out. Hopefully you'll have some better marketing and comparison by then ;)

**Comment by santacruz123** [comment]
It's not my framework, dinosaur ;)

**Pull request closed without merging**
