### PR TITLE
Add nanoid

### PR DESCRIPTION
**Pull request by florianb**
https://github.com/ai/nanoid is an actively maintained id-generator which compares best to UUIDv4 (random-based id generation) which generates ids with a similar collision probability, but less size (21 symbols vs 36) and ~16% faster. It has security in mind (using crypts random number generator and providing a company-backed disclosure procedure.

It is very helpful at any point heavily relying on collision-free ids, like f.e. cassandra or couchdb document-ids.

I don't know if mad science is the best category.

**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
It's not really mad science, but definitely useful.

**Comment by florianb** [comment]
You're right, i'd propose then **Text** or **Misc** (even though the latter is already pretty stuffed).

**Comment by sindresorhus** [comment]
`Text` then

**Comment by florianb** [comment]
Aye :vulcan_salute:

**Pull request merged**
