### PR TITLE
Add skale

### PR DESCRIPTION
**Pull request by mvertes**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by stefanjudis** [comment]
☝️ 

> Additions should be added to the bottom of the relevant category.

**Comment by mvertes** [comment]
Right. I will fix it. Thanks.

**Comment by sindresorhus** [comment]
What makes it "mad science"?

**Comment by mvertes** [comment]
Skale-engine is the only one generic and modern distributed data processing system that I know in the NodeJS ecosystem, with many similarities with Apache Spark, and also with higher performances. It's an effort (too rare in my opinion) to push NodeJS towards high performance and distributed computing (including machine learning) and serious/large data crunching, where V8 and Node architecture is potentially superior to the dominant one (JVM).

**Pull request merged**
