### PR TITLE
Add Terminalizer

### PR DESCRIPTION
**Pull request by faressoft**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by faressoft** [comment]
terminalizer

It is the #1 trending repo on GitHub

**Comment by faressoft** [comment]
@sindresorhus I agree with you about exporting an SVG. I will do that, it is matter of time. Last week I released terminalizer-player and going to publish terminalizer.com soon.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome-nodejs/pull/843/files#r224952312

**Comment by sindresorhus** [comment]
Bump

https://github.com/sindresorhus/awesome-nodejs/pull/843#discussion_r224952312

**Pull request closed without merging**
