### PR TITLE
Add DraftLog to the list of CLI utilities

### PR DESCRIPTION
**Pull request by ivanseidel**
This might look like the existing `log-update`, but it's more simple and accepts multiple updates concurrently.

The Gif says what it can do, and the docs even more: [https://github.com/ivanseidel/node-draftlog](https://github.com/ivanseidel/node-draftlog)

DraftLog GIF

**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
> By submitting this pull request, I promise I have read the contribution guidelines twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖

**Comment by ivanseidel** [comment]
`?` If you just created something, wait at least 30 days before submitting. This is to give it some time to mature and ensure it's not just a publish-and-forget type of project.
✔ Keep in mind that the list is very mature by now, so the bar of getting something accepted is high. Only submit something unique and generally useful. The world (and this list) doesn't need yet another ORM or framework. For CLI tools, the bar is especially high, and unless it's something very awesome, I would suggest submitting to awesome-cli-apps instead.
✔ If you submit a project that is similar to an existing project in the list, argument how it's better.
✔ Search previous suggestions before making a new one, as yours may be a duplicate.
✔ Suggested packages should be tested and documented.
✔ Make an individual pull request for each suggestion.
✔ Use the following format: [package](link) - Description.
✔ Additions should be added to the bottom of the relevant category.
✔ Link to the GitHub repo, not npmjs.com.
✔ Keep descriptions short and simple, but descriptive.
✔ Don't mention Node.js in the description as it's implied.
✔ Start the description with a capital and end with a full stop/period.
✔ Don't start the description with A or An.
✔ Check your spelling and grammar.
✔ Make sure your text editor is set to remove trailing whitespace.
✔ The pull request should have a useful title and include a link to the package and why it should be included.
`N/A` New categories or improvements to the existing categorization are welcome, but should be done in a separate pull request

By logic, I say that the only reason is Time. Not sure how a maturity can be measured by a threshold, but surely is something to make it easy to manage Awesome Lists.

If that's the only reason, shall we just let the time pass?

**Comment by sindresorhus** [comment]
> If that's the only reason, shall we just let the time pass?

Yes, that's what it says.

**Comment by ivanseidel** [comment]
One suggestion: Cleanup the list.

There are many items with replicate idea or really low utility in the list. For me, less than 1/4 is considered "Awesome" in the CLI tools. Many don't even have at least 50 lines of code.

Worth consider cleaning up since "the bar is especially high", but with so many not awesome at all tools. Gives space for cool projects

anyway, just a suggestion. ;)

Will notify in 26 days 21 hours and 14 minutes

**Pull request closed without merging**
