### PR TITLE
Added dns-zonefile

### PR DESCRIPTION
**Pull request by elgs**
https://github.com/elgs/dns-zonefile

### CODE REVIEW

**Comment by sindresorhus** [comment]
When would I use something like this?

**Comment by elgs** [comment]
@sindresorhus `dns-zonefile` is to parse a zone file to JSON format, and to generate a JSON file to zone file format. This is useful for parsing, generating or manipulating DNS zone files. `dns-zonefile` is used by Google Cloud Platform for their Node.js client: https://github.com/googlecloudplatform/gcloud-node.

**Comment by sindresorhus** [comment]
I read the readme on what it does, I'm just unsure in what situation I would use this. I'm trying to keep the list to what people would frequently need and I can't see what I would use this for in my projects.

**Comment by sindresorhus** [comment]
Gonna pass on it for the above reason. Sorry. I need to be picky on what I include otherwise it's no better than the npm search.

**Pull request closed without merging**
