### PR TITLE
Add `stream-faqs`

### PR DESCRIPTION
**Pull request by stephenplusplus**
I made a FAQ for streams that tries to address some common, real-world, production use cases, where left to the Node.js manual and google, you'd be lost.

https://github.com/stephenplusplus/stream-faqs

Hope this is the right fit, and the right category! (Cheatsheets?)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Ah yeah. How could I forget adding it here.

**Comment by stephenplusplus** [comment]
Cause you have 60 thousand other issues to deal with :)

Thanks!

**Comment by arthurvr** [comment]
Neat work @stephenplusplus!

**Comment by stephenplusplus** [comment]
Thanks! :D

**Pull request merged**
