### PR TITLE
Add mzsi package under miscellaneous section.

### PR DESCRIPTION
**Pull request by cauealves**

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Could you adhere to the contribution guidelines. Especially the last one https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md

**Comment by cauealves** [comment]
@SamVerschueren Oh, sorry. I did not notice the last line.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I don't think this is generally useful enough to be in this list.

**Comment by cauealves** [comment]
Yeah. thanks @sindresorhus :)

**Comment by sindresorhus** [comment]
You could try https://github.com/aharris88/awesome-cli-apps ;)

**Pull request closed without merging**
