### PR TITLE
Build an Alexa Skill using Node.js (https://medium.com/coinmonks/how-to-develop-an-amazon-alexa-skill-using-node-js-b872ef5320b1)

### PR DESCRIPTION
**Pull request by AjayAgAI**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

 A tutorial that will guide you through all the steps towards making an Alexa Skill using Node.js which you can launch in the Amazon Market. Building an Alexa Skill is extremely great way of introducing Node to the newcomers in the field. They can realize the power of Node.js and get a motivation to continue their journey towards further learning the language.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please follow the contribution guidelines.

**Comment by AjayAgAI** [comment]
I would like to know what rule of the guidelines I am not following. Apart from the fact that my description contains the word Node.js, there isn't any specific rule that my pull request that breaks .

**Comment by bruchmann** [comment]
> The pull request should have a useful title and include a link to the package and why it should be included.

**Comment by AjayAgAI** [comment]
@bruchmann and @sindresorhus  I had updated the pull request as per the contribution guidelines. Please review the changes.

**Comment by sindresorhus** [comment]
Just go through the list of guidelines and you’ll see that it still doesn’t follow. I’m not trying to be difficult, but I spent a lot of time on the guidelines so I wouldn’t have to point out everything manually.

**Pull request closed without merging**
