### PR TITLE
Add Endb

### PR DESCRIPTION
**Pull request by chroventer**
# Endb
> 🗃 Simple key-value storage with support for multiple backends.

## Features
- **Easy-to-use**: *Endb* has a simplistic and easy-to-use promise-based API.
- [**Adapters**](#Usage): By default, data is stored in memory. You can optionally install and utilize a "storage adapter".
- [**Third-Party Adapters**](#Third-Party-Adapters): You can optionally utilize third-party adapters or build your own. *Endb* will integrate the third-party adapter and handle complex data types internally.
- [**Namespaces**](#Namespaces): Namespaces isolate elements within a database.
- [**Custom Serializers**](#Custom-Serializers): Utilizes data serialization to ensure consistency across different backends.
- [**Embeddable**](#Embeddable): *Endb* is designed to be easily embeddable inside modules.
- **Data Types**: Handles all the JSON types including [`Buffer`](https://nodejs.org/api/buffer.html).
- **Error-Handling**: Connection errors are sent through, from the adapter to the main instance; connection errors won't exit or kill the process.
- [**Custom Serializers**](#Custom-Serializers): Utilizes data serialization methods that encode Buffer data as a base64-encoded string, and decode JSON objects which contain buffer-like data (either as arrays of numbers or strings) into Buffer instances to ensure consistency across different backends.
Optionally, pass your own data serialization methods to support extra data types.
- **Data Types**: Handles all the JSON types including [`Buffer`](https://nodejs.org/api/buffer.html) using its data serialization methods.
- **Error-Handling**: Connection errors are sent through, from the adapter to the main instance; connection errors won't exit or kill the process.

## Useful Links
- [Documentation](https://endb.js.org "Documentation")
- [GitHub](https://github.com/chroventer/endb "GitHub")
- [NPM](https://npmjs.com/package/endb "NPM")

**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
Duplicate of #965

**Comment by chroventer** [comment]
Hey @sindresorhus,
I have deleted the pull-request branch for the previous pull-request, not only that, but Endb has changed a lot since then. Therefore, I created a new pull-request addressing all the issues with the previous submission.

**Comment by sindresorhus** [comment]
Last time, I asked you a question and you just ignored it. You have still not answered it.

**Comment by chroventer** [comment]
> Last time, I asked you a question and you just ignored it. You have still not answered it.

You see Endb has changed its implementation, that is, from ORM type database to key-value type database. Thus, the question is no longer valid. Further, I am sorry for that.

**Comment by chroventer** [comment]
> Last time, I asked you a question and you just ignored it. You have still not answered it.

I am sorry for not answering that question. You see Endb has improved and developed significantly and as it did, the question became unreasonable and unrelated to Endb. Again, I am sorry for not reporting this earlier. I have replied to that comment recently.

**Pull request closed without merging**
