### PR TITLE
add webapplog.com/tag/node-js

### PR DESCRIPTION
**Pull request by azat-co**
- [webapplog.com](http://webapplog.com/tag/node-js/) — Blog posts on Node.js and JavaScript from the author of Practical Node.js and Pro Express.js Azat Mardan

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md

**Comment by azat-co** [comment]
@sindresorhus i saw that but what you don't like in my PR?

**Comment by sindresorhus** [comment]
The contributing guidelines are there so I don't have to waste time pointing it out to everyone...

> Start the description with a capital and **end with a full stop/period**.

**Comment by azat-co** [comment]
@sindresorhus i added the period.

**Comment by azat-co** [comment]
@sindresorhus thank you!

**Pull request closed without merging**
