### PR TITLE
Add cross-env

### PR DESCRIPTION
**Pull request by kentcdodds**

### CODE REVIEW

**Comment by sindresorhus** [comment]
The description needs work.

**Comment by kentcdodds** [comment]
Yeah, I struggled with it. How about:

```
Set environment variables in scripts with unix style and it still works on Windows.
```

I'm not a huge fan of that either... :-/

**Comment by sindresorhus** [comment]
> Set environment variables cross-platform.

**Comment by sindresorhus** [comment]
You should also add it here: https://github.com/bcoe/awesome-cross-platform-nodejs

**Comment by SamVerschueren** [comment]
```
Expose unix style environment variables cross-platform
```

Or what Sindre said :)

**Comment by kentcdodds** [comment]
Updated. Thanks!

**Pull request merged**
