### PR TITLE
Add modern-node

### PR DESCRIPTION
**Pull request by sheerun**
https://github.com/sheerun/modern-node

> For CLI tools, the bar is especially high, and unless it's something very awesome

I think it's awesome through the roof but it's up to you to decide :P

This project is similar just to your boilerplate but works differently:

1. It's not meant for cloning but installing or creating with `create-modern-node`
2. It uses jest instead of ava, it uses prettier+eslint+standard instead of xo
3. It has built in precommit hook so installing husky is not necessary

I've put it next to your package instead of at the bottom because these two are most similar in functionality.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think the naming is unfortunate. It has the same problem as Standard. The naming fools people into thinking this is the "modern" way of doing node modules, while it's really just your opinionated preference, just like Standard.

**Comment by sindresorhus** [comment]
I mean, I’m not saying I won’t accept it, but maybe you want to do something about the marketing?

**Comment by sheerun** [comment]
Unfortunately I cannot change name of module, but I've changed marketing to "Toolkit for creating node modules with Jest testing, Prettier formatting, and Standard linting" for now

**Comment by sheerun** [comment]
I've updated description here as well

**Pull request merged**
