### PR TITLE
Add Ejs

### PR DESCRIPTION
**Pull request by hetz**
EJS is template module, very popular.

### CODE REVIEW

**Comment by hetz** [comment]
Hi ,@sbruchmann 

I fix typo,thx.

**Comment by kevva** [comment]
@hetz, please don't create new PRs. Push to the old branch instead.

**Comment by hetz** [comment]
@kevva ,so sorry, I don't know this rule.

pls tell me, what should I do next.

**Comment by kevva** [comment]
@hetz, nothing. But in future PR's, just push to your forked branch and the PR will update automatically.

**Pull request closed without merging**
