### PR TITLE
Add node-fetch

### PR DESCRIPTION
**Pull request by bitinn**
It's recommended on the [github/fetch](https://github.com/github/fetch#installation) and works with [form-data](https://github.com/form-data/form-data), also served as a base for [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch). Full disclosure: I wrote it :)

### CODE REVIEW

**Comment by lirantal** [comment]
+1

**Comment by sbruchmann** [comment]
@lirantal You can add ‘reactions’ to issues. Please read [this blog post](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments).

**Comment by Pines-Cheng** [comment]
I like it.

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by bitinn** [comment]
@sindresorhus OK, looks like I missed a period... just a few questions:

1. using `Node.js` in this instance is fine right?
2. Do I need to rebase my PR?

**Comment by sindresorhus** [comment]
1. Yes, but capitalize it correctly.
2. No, just add another commit with the fixes.

**Comment by bitinn** [comment]
@sindresorhus done

**Pull request closed without merging**
