### PR TITLE
Add pg-promise

### PR DESCRIPTION
**Pull request by vitaly-t**
Adding [pg-promise](https://github.com/vitaly-t/pg-promise) - promise-based high-level framework for PostgreSQL.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by vitaly-t** [comment]
>Please read and adhere to the contributing guidelines.

I did that. Are you saying that I missed something? It would help if you point it out then.

**Comment by vitaly-t** [comment]
@sindresorhus I've gone through the requirements 5 times, I don't see anything where this PR wouldn't adhere to. So what is wrong with this PR?

**Comment by KapuzenSohn** [comment]
One thing is to give the Pull request a good name

**Comment by vitaly-t** [comment]
>One thing is to give the Pull request a good name

Ok, done! :)

**Comment by KapuzenSohn** [comment]
For me the Pull request still says `Update readme.md`

**Comment by vitaly-t** [comment]
>For me the Pull request still says Update readme.md

I don't know why it changed back, so I changed it again.

**Pull request closed without merging**
