### PR TITLE
Add Gatsby

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by KyleAMathews** [comment]
I read it and am not sure what you want changed.

**Comment by SamVerschueren** [comment]
> Use the following format: `[package](link) - Description.`

Start your description with a capital.

**Comment by KyleAMathews** [comment]
@SamVerschueren ah thanks! Pushed fix.

**Comment by youfoundron** [comment]
@KyleAMathews - should re-open this one

**Pull request closed without merging**
