### PR TITLE
Add oboe into HTTP section

### PR DESCRIPTION
**Pull request by ecancino**
Link: http://oboejs.com/

Oboe.js is an open source Javascript library for loading JSON using streaming, combining the convenience of DOM with the speed and fluidity of SAX.

It can parse any JSON as a stream, is small enough to be a micro-library, doesn’t have dependencies, and doesn’t care which other libraries you need it to speak to.

We can load trees larger than the available memory. Or we can instantiate a classical OOP models from JSON, or completely transform your JSON while it is being read.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Looks ok, but I'm gonna pass on it as the project is not actively maintained and haven't seen much activity since one and a half years ago. Happy to reconsider if someone takes of maintainership or any good other module that solves the same problem.

**Comment by ecancino** [comment]
@jimhigson @JuanCaicedo What is the maintenance plan for this project?

**Comment by JuanCaicedo** [comment]
I think @jimhigson doesn't have much time to work on it. I'm interested in helping out more, but haven't been able to chat with him to get that started. Basically need to figure out how to accept contributions and how to push new version to NPM. I'm glad to make a PR here once that's figured out

**Comment by JuanCaicedo** [comment]
@ecancino I just published a new version to npm and am actively working on oboe. Would love to see this PR opened again if it sounds good to @sindresorhus ! 😃

**Pull request closed without merging**
