### PR TITLE
Add discharge

### PR DESCRIPTION
**Pull request by brandonweiss**
[Discharge](https://github.com/brandonweiss/discharge) is, as far as I’m aware, the easiest way to deploy static websites to Amazon S3. It can also configure an SSL certificate and distribute the site via CloudFront, all without having to know anything about AWS. I spent hours poring over AWS’s terrible docs so no one else would have to. There is also a prompt-based UI to help you configure it. And it’s very well documented.

Thanks for considering!

**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
Very nice! I like tools that simplify complex tasks in a user-friendly way.

**Comment by sindresorhus** [comment]
The description has both "simple" and "easy" in it, which means the same. I changed it to `Easily deploy static websites to Amazon S3.`, which I think reads better.

**Comment by sindresorhus** [comment]
I would also consider finding a better name for it. Try Googling the word "discharge".

**Comment by brandonweiss** [comment]
Thanks! ❤️

Haha, yeah, not everyone is thrilled about the name. 😂 I know it has some gross connotations, but the name worked too well with the NPM scope (@static/discharge) and a complementary static site generator I’m working on (@static/charge). I couldn’t resist. 😂

**Pull request merged**
