### PR TITLE
express-routemap added to list

### PR DESCRIPTION
**Pull request by izelnakri**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Please read and adhere to the [contributing guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md).

**Comment by izelnakri** [comment]
I've read it before submitting the PR, which part did I miss to read?

**Comment by SamVerschueren** [comment]
> Use the following format: [package](link) - Description.
> Additions should be added to the bottom of the relevant category.

**Comment by izelnakri** [comment]
and what should I do differently?

**Comment by sruf** [comment]
**bottom** of the relevant category. End with fullstop/period.

**Comment by izelnakri** [comment]
instead of criticizing, could you please tell me which category you would like this to be in?

**Comment by SamVerschueren** [comment]
The keyword is **bottom**. You added it to  the top of the category, it has to be added as the last item instead of the first one.

**Comment by sruf** [comment]
I understand that English is not your first language. However, instead of getting defensive, would you please just read our replies as neutral, information-oriented help?

You're supposed to add a new package at the **bottom**, not at the top of the category; and, instead of ending on an exclamation mark, use a fullstop (->  "." )

Standardized formats are important for a variety of purposes.

**Comment by SamVerschueren** [comment]
An end with a full stop instead of an exclamation mark.

**Comment by izelnakri** [comment]
@sruf yep apparently I've read it fast and differently before you made the ```bottom``` bold, no need for further explanation. Adjusted it now.

**Comment by sruf** [comment]
As you can see, my first comment was never edited and always had "bottom" bold. I edited my later comment to correct punctuation and remove wording which might have caused an undesired impression of impatience on my side.

I'm glad you corrected your pull request. Happy 2017.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I'm going to pass on this. This is a curation, so I unfortunately can't include everything. That means making the hard decision of leaving out some cool projects for various reasons.

**Pull request closed without merging**
