### PR TITLE
add parcel, microbundle and sfo bundler

### PR DESCRIPTION
**Pull request by soenkekluth**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by bruchmann** [comment]
> By submitting this pull request, I promise I have read the contribution guidelines twice and ensured my submission follows it.

This is a blatant lie.

**Comment by SamVerschueren** [comment]
Please read and adhere to the [contributing guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md).

**Comment by soenkekluth** [comment]
@bruchmann it never was my intension not to follow the guidelines - well maybe i missed what you see. - just a little hint would be usefull - neither of these libs are from me. so my intension is just to complete the list for all others

**Comment by bruchmann** [comment]
Excerpts from the [contributing guidlines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md):

> • Make an individual pull request for each suggestion.
> • Start the description with a capital and end with a full stop/period.
> • The pull request should have a useful title and include a link to the package and why it should be included.

**Comment by SamVerschueren** [comment]
@soenkekluth feel free to make separate PRs and we will review them, no harm done :)

**Comment by StarpTech** [comment]
What a troll discussion. Let us drown in rules and guidelines for a simple list. @bruchmann your attitude is negative from the first contact that's not the way to go with someone who just wants to contribute.

**Comment by SamVerschueren** [comment]
Locking this conversation before it gets out of hand. Let's all be kind to each other 🎄 !

**Pull request closed without merging**
