### PR TITLE
Add DraftLog

### PR DESCRIPTION
**Pull request by ivanseidel**
Now, this is the first minute that the project became "Mature".

This might look like the existing `log-update`, but it's much better, by offering a more simple and api that accepts multiple updates concurrently.

The Gif says what it can do, and the docs even more: [https://github.com/ivanseidel/node-draftlog](https://github.com/ivanseidel/node-draftlog)

DraftLog GIF

**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by ivanseidel** [comment]
Ping

**Comment by thetutlage** [comment]
It's kind of sad to see quality projects are out and there are bunch of low quality projects are hanging around in README

I respect that you are strict with submissions but also at times it is important to filter out what's already in and open room for other projects.

## Just to mention

1. Derby is no where a quality project, last issue was resolved in 2015 and look at the quality of docs.
2. Can someone tell me why http://restberry.com/ is in the list of frameworks?
3. Same is the story with Waterline ORM, there are bunch of weird issues and ORM misses basic functionality like selecting fields https://github.com/balderdashy/waterline/issues/73

It will be nice to re-consider some packages, which works seamlessly and remove those which are eating others space.

**Comment by sindresorhus** [comment]
@ivanseidel I'm traveling at the moment. I'll review the open PRs soon :)

@thetutlage Totally agree. Can you move your comment into a new issue? Let me know if there are more.

**Comment by thetutlage** [comment]
Yup will do that for sure

**Comment by sindresorhus** [comment]
Added. Sorry about the delay.

**Comment by sindresorhus** [comment]
@thetutlage I've removed Derby and Restberry. Not sure about Waterline. It seems very popular and the blog post you linked to is 2 years old. It might have gotten better since then?

**Pull request merged**
