### PR TITLE
Add Sails.js

### PR DESCRIPTION
**Pull request by vishwasraj**
The Sails.js framework is quite a famous one, but missing from the list.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but Sails.js is terrible, and also not actively maintained anymore.

**Comment by bitbreakr** [comment]
@sindresorhus , just curious, what makes you think Sails.js is a terrible framework ? (by the way, I love your work 🥇 )

**Comment by sindresorhus** [comment]
- https://news.ycombinator.com/item?id=16750150
- https://kevin.burke.dev/kevin/dont-use-sails-or-waterline/

**Comment by mikermcneil** [comment]
Just want to clear things up here: the Sails framework is actively maintained and widely used.  For context, I am its creator and BDFL.  @rachaelshaw is lead maintainer, and @eashaw is community manager.  @DominusKelvin also maintains an active supplementary community called SailsCasts.  https://sailsjs.com/support has a full list of resources you might want to check out.  As far as what that means: there's a daily check for vulnerable code paths, a weekly roundup of community GitHub issues/PRs, and active development as needed to fix any priority bugs.  This is all funded by Flagship customers and supplemented by my continued personal financial commitment to keep the Sails framework alive.  

This will continue for many years to come.

image
image
image
image
image


See also #1028 #998 #682 #380 #6

**Comment by DominusKelvin** [comment]
Thanks @mikermcneil for mentioning me. Like Mike said, Sails is actively being maintained with a strong active community. 

I started my company The Sailscasts Company primarily to build [Sailscasts](https://sailscasts.com) - a platform to teach Sails to JavaScript developers and we'll be launching by March 17, 2021.

The Sailscasts Company also build custom Node.js solutions for our clients based on Sails.

I have created an [open source web API](https://github.com/Wavesafrica/waves-africa-api) based on Sails powering a telegram bot and used by other clients.


You can check out the [Sailscasts blog](https://blog.sailscasts.com) and also join the [workshop](https://nodecongress.com/workshops-3h) I will be giving on Sails at Node Congress by Thursday :)

**Pull request closed without merging**
