### PR TITLE
Add General category under Control flow

### PR DESCRIPTION
**Pull request by faressoft**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by faressoft** [comment]
To add Flowa under it as next step

**Comment by faressoft** [comment]
@cortezcristian

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I'm going to pass on Flowa.

**Comment by faressoft** [comment]
@sindresorhus Thanks, I don't think it fits under any of the categories under "Control flow".

Here it is
[https://github.com/faressoft/flowa](https://github.com/faressoft/flowa)

**Pull request closed without merging**
