### PR TITLE
Add Napi-RS under new category (cross-platform integration)

### PR DESCRIPTION
**Pull request by robinrodricks**
Hi there! Thanks for running this awesome list.

This PR is to add [NAPI-RS ](https://napi.rs/) to a new "cross-platform integration" section.

**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
I prefer to not create categories until there are at least two entries for it.

**Comment by robinrodricks** [comment]
I wanted to add these as well, all major projects, all under the same category:

- [Edge.js](https://github.com/tjanczuk/edge) - Run .NET and Node.js code in-process on Windows, MacOS, and Linux
- [DotNetJS](https://github.com/Elringus/DotNetJS) - Consume C# libraries in Node.js with comfort
- [Neon](https://github.com/neon-bindings/neon) - Rust bindings for writing safe and fast native Node.js modules.

**Comment by robinrodricks** [comment]
@sindresorhus Can you let me know pls?

**Comment by sindresorhus** [comment]
👍

**Comment by robinrodricks** [comment]
What does that mean, are you gonna approve this, or should I edit the PR to add all 4 projects?

**Comment by robinrodricks** [comment]
@sindresorhus I have added 4 projects, please check.

**Comment by robinrodricks** [comment]
Thank you.

**Pull request merged**
