### PR TITLE
Add toxy package

### PR DESCRIPTION
**Pull request by h2non**
Adds [toxy](https://github.com/h2non/toxy) in HTTP section (however, I'm not completely sure about this, maybe in testing section makes sense as well).

### CODE REVIEW

**Comment by sindresorhus** [comment]
The `Testing` section might make more sense as that's where I would use it.

**Comment by h2non** [comment]
@sindresorhus got it!

**Comment by sindresorhus** [comment]
You should probably learn how to do pull requests correctly. Look at the top commit mess. Never do a pull request from `master`. http://stackoverflow.com/a/14681796/64949

**Comment by h2non** [comment]
I see, sorry about that! Definitely this repository is too active to work in master.

**Comment by sindresorhus** [comment]
> Definitely this repository is too active to work in master.

Not this repository's master, your fork's master. You included commits from your last pull request in this one.

**Comment by h2non** [comment]
Yes, my branch was master, that's the problem. I should do it in another one, and then pull to master. 

Got it for the next time :+1:

**Pull request closed without merging**
