### PR TITLE
Add taskbook

### PR DESCRIPTION
**Pull request by novddd**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

A minor change that adds [taskbook](https://github.com/klauscfhq/taskbook) 😄

### CODE REVIEW

**Comment by omangaresu** [comment]
A project must be 30 plus more to be added ,but this was created long time ago , here is first commit https://github.com/klauscfhq/taskbook/commit/e70fd44efbe3a5200b427333fca5f0ed5a37ecaa 
other than that i can;t say with security

**Comment by novddd** [comment]
I fixed a small conlfict! 😄 @omangaresu Maybe Sindre knows what to do 😄 🚀

**Comment by novddd** [comment]
Hi @sindresorhus ! Is this pr ok? Should i maybe delete it? Sorry for bothering you again ❤️

**Comment by novddd** [comment]
I think this pull request has achieved 30 days! 🎉🎉

**Comment by sindresorhus** [comment]
Thanks for the suggestion :)

**Pull request merged**
