### PR TITLE
Add nulldog.com

### PR DESCRIPTION
**Pull request by molcik**
Add nulldog.com website into resources/blogs section.

**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
These articles feels AI generated.

**Comment by molcik** [comment]
Yes, but are also human-checked, topics are hand pick and user feedback is collected to adjust them. I have added also disclosure into the footer and front page so it's more clear. I still find information in it valuable as generating these takes time (here are "cached") and expertise (you need to know what to ask and check it). But it's up to you if it has value for the list.

**Comment by sindresorhus** [comment]
I'm going to pass on this. It feels too much like SEO farming.

**Comment by molcik** [comment]
I see, are there any features or changes, I can make that would make you reconsider it?

**Pull request closed without merging**
