### PR TITLE
Add n2words

### PR DESCRIPTION
**Pull request by forzagreen**
[n2words](https://github.com/forzagreen/n2words) converts numbers to a human readable string. As of today, it supports 26 languages.

Examples:
```javascript
n2words(123)   // 'one hundred and twenty-three'
n2words(-1.5)  // 'minus one point five'

n2words(123, {lang: 'fr'})  // 'cent vingt-trois'
n2words(123, {lang: 'es'})  // 'ciento veintitrés'
n2words(123, {lang: 'ar'})  // 'مائة و ثلاثة و عشرون'
```
I put it under the _Humanize_ section. I could also go under _Natural language processing_.

### CODE REVIEW

**Review by dummib-3jYtco-qizgaw — APPROVED** [review]

**Comment by romankurnovskii** [comment]
What is the advantage over https://www.npmjs.com/package/to-words ?

**Comment by forzagreen** [comment]
@romankurnovskii n2words supports much more languages: 27 vs 9.

**Comment by romankurnovskii** [comment]
> 
I see 18, so this is a question, if the issue is only in amount of languages why not to add translation or there are some more features? I use this maintained package, just want to know if there is a good reason to look at something new

**Comment by forzagreen** [comment]
@romankurnovskii  
- No, there are only 9 languages. The 18 are "locales". For example, there are 10 locales for english (en-US, en-GB,...).
- Adding a new language is not just a matter of "translation". Each language has its own algorithm.
- n2words has much larger language coverage, i.e. it has major spoken languages that to-words doesn't have: Spanish, Arabic, Chinese, Russian, German...
- to-words seems to be adapted more for currencies.

**Comment by romankurnovskii** [comment]
> [forzagreen](/forzagreen)

thank you @forzagreen for explanation

**Comment by sindresorhus** [comment]
The package looks fine, but I don't think it's a common need. I try to curate the most common things users will need here. For this package, the user can easily search for it if they need it.

**Pull request closed without merging**
