### PR TITLE
Add Mariner and SailsJS frameworks

### PR DESCRIPTION
**Pull request by wilk**
**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
> By submitting this pull request, I promise I have read the contribution guidelines twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖

You did not:

> Make an individual pull request for each suggestion.

**Comment by sindresorhus** [comment]
And:

> If you just created something, wait at least 30 days before submitting. This is to give it some time to mature and ensure it's not just a publish-and-forget type of project.

**Comment by sindresorhus** [comment]
I'm not interested in including SailsJS. It's not something I would recommend.

As for Mariner, I think it needs more time to mature and have some production usage.

**Comment by wilk** [comment]
@sindresorhus I definitely didn't read the contribution guidelines, I'm very sorry for that.
Sorry again for wasting your time.

**Comment by sindresorhus** [comment]
Sorry, if it came out harsh. I just wanted to point it out. No hard feelings :)

**Pull request closed without merging**
