### PR TITLE
Add n8n

### PR DESCRIPTION
**Pull request by janober**
n8n is a free node based Workflow Automation Tool (Zapier/Tray.io alternative) which allows to easily automate tasks across different services.

It can be started and tested locally with:
```bash
npx n8n
```

The "node" in the description text describes the UI and not Node.js

Community Forum: https://community.n8n.io
Documentation: https://docs.n8n.io
Github: https://github.com/n8n-io/n8n
Website: https://n8n.io 

**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆

### CODE REVIEW

**Comment by sindresorhus** [comment]
Looks like a useful tool, but where can I find the release notes / changelog?

**Comment by janober** [comment]
Great to hear.!

There are currently no release notes or changelog except the ones in GitHub. For now, I simply try to make clearly visible in the commits when a new version got released:
https://github.com/n8n-io/n8n/commits/master

I have planned to add proper release/change notes in the next few months. For now, I simply have to be as efficient with my time as possible until I have hired an initial team.

Have only a separate file for breaking changes:
https://github.com/n8n-io/n8n/blob/master/packages/cli/BREAKING-CHANGES.md

**Comment by sindresorhus** [comment]
I'm going to pass on this for now for these reasons:
- Lack of changelog is a sign that it's not really ready for users to use it. If it's not a priority, users are not your priority yet. Which is fine, but this list is for users.
- There seems to be some [drama](https://github.com/n8n-io/n8n/issues/40) about whether the project is open source or not and I don't want to deal with that.

**Comment by janober** [comment]
Sure totally OK with me. However, do not I agree with your reasoning at all.

**Lack of changelog is a sign that it's not really ready for users to use it. If it's not a priority, users are not your priority yet. Which is fine, but this list is for users.**
Not sure if defining "not read to use" by the absence of changelog/release notes is correct, but ok. But saying the absence of it means users are not the priority (especially after having this pull-request open for 2 months!) feels almost like an insult. Because they are, and helping them, is actually my top priority!

 **There seems to be some drama about whether the project is open source or not and I don't want to deal with that.**
Even more confusing. You require that people read your "contribution guidelines" twice before opening a pull-request and then you apparently randomly add rules like needing changelog/release notes and that it is OSI approved open source. The last one is even more confusing as it is not called "awesome-osi-approved-open-source-nodejs" or even "awesome-open-source-nodejs rather just "awesome-nodejs" and open source is not mentioned anywhere at all. Also your description "Curating the best Node.js modules and resources" gives not any idication that it is in any way "open source" related. If it is, also fine. But please add it to your guidelines.

Thanks!

**Pull request closed without merging**
