### PR TITLE
Add `npm semver calculator`

### PR DESCRIPTION
**Pull request by Hongarc**
This page helps us find the version of that module on npm match range.

### CODE REVIEW

**Comment by Hongarc** [comment]
I created #927 with backtick :)

**Comment by Phrynobatrachus** [comment]
Yep, the description still doesn't quite match my suggestion though.

``[npm semver calculator](https://semver.npmjs.com/) - Semantic version calculator, useful for determining match range in `package.json`.``

The beginning of the description is different and you're missing a period.

**Comment by sindresorhus** [comment]
There's never a need to open a new PR. Next time just push addition commits.

**Comment by Hongarc** [comment]
> There's never a need to open a new PR. Next time just push addition commits.

I know that, but I deleted that fork repo so I push a commit to that branch but it doesn't update.

**Comment by sindresorhus** [comment]
> but I deleted that fork repo

Don't do that.

**Pull request merged**
