### PR TITLE
Add Bit

### PR DESCRIPTION
**Pull request by jonisar**
Added bit under miscellaneous for exporting, storing, managing, discovering and reusing small modules in any context across projects.
NPM: https://www.npmjs.com/package/bit-bin

**By submitting this pull request, I promise I have read the [contribution guidelines](https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:45.833333333333336% 2.0833333333333335%;background-size:4900%" data-codepoints="1f596"></span></span>**

<span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 83.33333333333334%;background-size:4900%" data-codepoints="2b06"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 83.33333333333334%;background-size:4900%" data-codepoints="2b06"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 83.33333333333334%;background-size:4900%" data-codepoints="2b06"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 83.33333333333334%;background-size:4900%" data-codepoints="2b06"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 83.33333333333334%;background-size:4900%" data-codepoints="2b06"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 83.33333333333334%;background-size:4900%" data-codepoints="2b06"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 83.33333333333334%;background-size:4900%" data-codepoints="2b06"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 83.33333333333334%;background-size:4900%" data-codepoints="2b06"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 83.33333333333334%;background-size:4900%" data-codepoints="2b06"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:6.25% 83.33333333333334%;background-size:4900%" data-codepoints="2b06"></span></span>

### CODE REVIEW

**Comment by sindresorhus** [comment]
Wouldn't it be better to place this under the Command-line tools section?

**Comment by jonisar** [comment]
Yes it would :)
Closing and PRing it under Command-line tools.

**Comment by sindresorhus** [comment]
Just edit the existing PR. No need to creat additional noise with a new PR.

**Comment by jonisar** [comment]
done.

**Pull request merged**
