### PR TITLE
Add mississippi - collection of useful stream modules

### PR DESCRIPTION
**Pull request by darrrk**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by darrrk** [comment]
Updated to be on bottom

**Comment by kevva** [comment]
Not sure why you would need a module like that will all those dependencies (most which are already included on this list),

**Comment by sindresorhus** [comment]
Yeah, it's a very useful guide on which modules to use, but I don't want to recommend users using just an exported collection of existing modules.

**Pull request closed without merging**
