### PR TITLE
Adds a tutorial reference

### PR DESCRIPTION
**Pull request by hegdeashwin**

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md

- Fix merge conflict
- Better title
- Description is incorrect

**Comment by hegdeashwin** [comment]
Hey @sindresorhus,
I have fixed the title and description.

**Comment by sindresorhus** [comment]
Looked through the content and gonna pass on this for now. The online example doesn't work. The only content I could find are two short slides. Try again in some months when it's in a better shape ;)

**Comment by hegdeashwin** [comment]
Certainly @sindresorhus ; :+1: I will try again after i sharing it better then what it is now.

**Comment by fizzvr** [comment]
nice try :+1:

**Pull request closed without merging**
